name: Playwright Python Tests (pytest-html)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install browsers
        run: |
          python -m playwright install --with-deps

      - name: Run pytest with HTML report
        run: |
          pytest --html=report.html --self-contained-html

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

      - name: Deploy HTML report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages

